
import "./globals.css";
import Navbar from "@/componets/Navbar";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       
      >
       <div className="max-w-3xl mx-auto"> 
         <Navbar/>
        {children}
       </div>
      </body>
    </html>
  );
}
